export const buttonIcons = [
  {
    name: 'Arrow',
    value: '/Static/dist/msds-spritemap.svg#right-arrow',
    previewValue: '#right-arrow'
  },
  { name: 'Mail', value: '/Static/dist/msds-spritemap.svg#email', previewValue: '#email' },
  { name: 'Devices Mobile', value: '/Static/dist/msds-spritemap.svg#phone', previewValue: '#phone' },
  { name: 'Close', value: '/Static/dist/msds-spritemap.svg#cross', previewValue: '#cross' },
  { name: 'Access', value: '/Static/dist/msds-spritemap.svg#access', previewValue: '#access' },
  { name: 'Arrow Double', value: '/Static/dist/msds-spritemap.svg#arrow-double', previewValue: '#arrow-double' },
  { name: 'Article', value: '/Static/dist/msds-spritemap.svg#article', previewValue: '#article' },
  { name: 'Attachment', value: '/Static/dist/msds-spritemap.svg#attachment', previewValue: '#attachment' },
  { name: 'Attention', value: '/Static/dist/msds-spritemap.svg#attention', previewValue: '#attention' },
  { name: 'Bell', value: '/Static/dist/msds-spritemap.svg#bell', previewValue: '#bell' },
  { name: 'Calendar', value: '/Static/dist/msds-spritemap.svg#calendar', previewValue: '#calendar' },
  { name: 'Career', value: '/Static/dist/msds-spritemap.svg#career', previewValue: '#career' },
  { name: 'Certification', value: '/Static/dist/msds-spritemap.svg#certification', previewValue: '#certification' },
  { name: 'Chat Headset', value: '/Static/dist/msds-spritemap.svg#chat-headset', previewValue: '#chat-headset' },
  { name: 'Chat', value: '/Static/dist/msds-spritemap.svg#chat', previewValue: '#chat' },
  { name: 'Checkmark', value: '/Static/dist/msds-spritemap.svg#checkmark', previewValue: '#checkmark' },
  { name: 'Clock', value: '/Static/dist/msds-spritemap.svg#clock', previewValue: '#clock' },
  { name: 'Cloud', value: '/Static/dist/msds-spritemap.svg#cloud', previewValue: '#cloud' },
  { name: 'Code', value: '/Static/dist/msds-spritemap.svg#code', previewValue: '#code' },
  { name: 'Colleague', value: '/Static/dist/msds-spritemap.svg#colleague', previewValue: '#colleague' },
  { name: 'Conference', value: '/Static/dist/msds-spritemap.svg#conference', previewValue: '#conference' },
  { name: 'Customer Story', value: '/Static/dist/msds-spritemap.svg#customer-story', previewValue: '#customer-story' },
  { name: 'Demo', value: '/Static/dist/msds-spritemap.svg#demo', previewValue: '#demo' },
  {
    name: 'Devices Desktop',
    value: '/Static/dist/msds-spritemap.svg#devices-desktop',
    previewValue: '#devices-desktop'
  },
  { name: 'Devices Tablet', value: '/Static/dist/msds-spritemap.svg#devices-tablet', previewValue: '#devices-tablet' },
  { name: 'Download', value: '/Static/dist/msds-spritemap.svg#download', previewValue: '#download' },
  { name: 'Drag', value: '/Static/dist/msds-spritemap.svg#drag', previewValue: '#drag' },
  { name: 'Edit', value: '/Static/dist/msds-spritemap.svg#edit', previewValue: '#edit' },
  { name: 'Elearning', value: '/Static/dist/msds-spritemap.svg#elearning', previewValue: '#elearning' },
  { name: 'Expertise', value: '/Static/dist/msds-spritemap.svg#expertise', previewValue: '#expertise' },
  { name: 'Extend', value: '/Static/dist/msds-spritemap.svg#extend', previewValue: '#extend' },
  { name: 'Filter', value: '/Static/dist/msds-spritemap.svg#filter', previewValue: '#filter' },
  { name: 'Grid', value: '/Static/dist/msds-spritemap.svg#grid', previewValue: '#grid' },
  { name: 'Home', value: '/Static/dist/msds-spritemap.svg#home', previewValue: '#home' },
  { name: 'Image', value: '/Static/dist/msds-spritemap.svg#image', previewValue: '#image' },
  { name: 'Information', value: '/Static/dist/msds-spritemap.svg#information', previewValue: '#information' },
  { name: 'IP Cameras', value: '/Static/dist/msds-spritemap.svg#ip-cameras', previewValue: '#ip-cameras' },
  { name: 'Knowledgebase', value: '/Static/dist/msds-spritemap.svg#knowledgebase', previewValue: '#knowledgebase' },
  { name: 'Like', value: '/Static/dist/msds-spritemap.svg#like', previewValue: '#like' },
  { name: 'Link', value: '/Static/dist/msds-spritemap.svg#link', previewValue: '#link' },
  {
    name: 'List-horisontal',
    value: '/Static/dist/msds-spritemap.svg#list-horisontal',
    previewValue: '#list-horisontal'
  },
  { name: 'Live', value: '/Static/dist/msds-spritemap.svg#live', previewValue: '#live' },
  { name: 'Location', value: '/Static/dist/msds-spritemap.svg#location', previewValue: '#location' },
  { name: 'Lock Closed', value: '/Static/dist/msds-spritemap.svg#lock-closed', previewValue: '#lock-closed' },
  { name: 'Lock Open', value: '/Static/dist/msds-spritemap.svg#lock-open', previewValue: '#lock-open' },
  { name: 'LPR', value: '/Static/dist/msds-spritemap.svg#lpr', previewValue: '#lpr' },
  { name: 'Menu', value: '/Static/dist/msds-spritemap.svg#menu', previewValue: '#menu' },
  { name: 'Minus', value: '/Static/dist/msds-spritemap.svg#minus', previewValue: '#minus' },
  { name: 'Network', value: '/Static/dist/msds-spritemap.svg#network', previewValue: '#network' },
  { name: 'No Access', value: '/Static/dist/msds-spritemap.svg#no-access', previewValue: '#no-access' },
  { name: 'Number 1', value: '/Static/dist/msds-spritemap.svg#number-1', previewValue: '#number-1' },
  { name: 'Number 2', value: '/Static/dist/msds-spritemap.svg#number-2', previewValue: '#number-2' },
  { name: 'Number 3', value: '/Static/dist/msds-spritemap.svg#number-3', previewValue: '#number-3' },
  { name: 'Number 4', value: '/Static/dist/msds-spritemap.svg#number-4', previewValue: '#number-4' },
  { name: 'Number 5', value: '/Static/dist/msds-spritemap.svg#number-5', previewValue: '#number-5' },
  { name: 'Observe', value: '/Static/dist/msds-spritemap.svg#observe', previewValue: '#observe' },
  { name: 'Operator', value: '/Static/dist/msds-spritemap.svg#operator', previewValue: '#operator' },
  { name: 'Pause', value: '/Static/dist/msds-spritemap.svg#pause', previewValue: '#pause' },
  { name: 'Play', value: '/Static/dist/msds-spritemap.svg#play', previewValue: '#play' },
  { name: 'Plug And Play', value: '/Static/dist/msds-spritemap.svg#plugandplay', previewValue: '#plugandplay' },
  { name: 'Plugin', value: '/Static/dist/msds-spritemap.svg#plugin', previewValue: '#plugin' },
  { name: 'Plus', value: '/Static/dist/msds-spritemap.svg#plus', previewValue: '#plus' },
  { name: 'Podcast', value: '/Static/dist/msds-spritemap.svg#podcast', previewValue: '#podcast' },
  { name: 'Press Release', value: '/Static/dist/msds-spritemap.svg#press-release', previewValue: '#press-release' },
  { name: 'Price', value: '/Static/dist/msds-spritemap.svg#price', previewValue: '#price' },
  { name: 'Print', value: '/Static/dist/msds-spritemap.svg#print', previewValue: '#print' },
  { name: 'Profile', value: '/Static/dist/msds-spritemap.svg#profile', previewValue: '#profile' },
  { name: 'Global', value: '/Static/dist/msds-spritemap.svg#publish', previewValue: '#publish' },
  { name: 'Question', value: '/Static/dist/msds-spritemap.svg#question', previewValue: '#question' },
  { name: 'Quote', value: '/Static/dist/msds-spritemap.svg#quote', previewValue: '#quote' },
  { name: 'Rating', value: '/Static/dist/msds-spritemap.svg#rating', previewValue: '#rating' },
  { name: 'Retail', value: '/Static/dist/msds-spritemap.svg#retail', previewValue: '#retail' },
  {
    name: 'Screen Recorder',
    value: '/Static/dist/msds-spritemap.svg#screen-recorder',
    previewValue: '#screen-recorder'
  },
  { name: 'Scroll', value: '/Static/dist/msds-spritemap.svg#scroll', previewValue: '#scroll' },
  { name: 'Search', value: '/Static/dist/msds-spritemap.svg#search', previewValue: '#search' },
  { name: 'Servers', value: '/Static/dist/msds-spritemap.svg#servers', previewValue: '#servers' },
  { name: 'Share', value: '/Static/dist/msds-spritemap.svg#share', previewValue: '#share' },
  { name: 'Smart Wall', value: '/Static/dist/msds-spritemap.svg#smart-wall', previewValue: '#smart-wall' },
  {
    name: 'Social Facebook',
    value: '/Static/dist/msds-spritemap.svg#social-facebook',
    previewValue: '#social-facebook'
  },
  {
    name: 'Social Instagram',
    value: '/Static/dist/msds-spritemap.svg#social-instagram',
    previewValue: '#social-instagram'
  },
  {
    name: 'Social Linkedin',
    value: '/Static/dist/msds-spritemap.svg#linkedin',
    previewValue: '#linkedin'
  },
  { name: 'Social Twitter', value: '/Static/dist/msds-spritemap.svg#social-twitter', previewValue: '#social-twitter' },
  { name: 'Social Youtube', value: '/Static/dist/msds-spritemap.svg#social-youtube', previewValue: '#social-youtube' },
  {
    name: 'Software Integration',
    value: '/Static/dist/msds-spritemap.svg#software-integration',
    previewValue: '#software-integration'
  },
  { name: 'Software', value: '/Static/dist/msds-spritemap.svg#software', previewValue: '#software' },
  { name: 'Solution', value: '/Static/dist/msds-spritemap.svg#solution', previewValue: '#solution' },
  { name: 'Sound', value: '/Static/dist/msds-spritemap.svg#sound', previewValue: '#sound' },
  {
    name: 'System Requirements',
    value: '/Static/dist/msds-spritemap.svg#system-requirements',
    previewValue: '#system-requirements'
  },
  { name: 'Tag', value: '/Static/dist/msds-spritemap.svg#tag', previewValue: '#tag' },
  { name: 'Transact', value: '/Static/dist/msds-spritemap.svg#transact', previewValue: '#transact' },
  { name: 'Trash', value: '/Static/dist/msds-spritemap.svg#trash', previewValue: '#trash' },
  { name: 'Update', value: '/Static/dist/msds-spritemap.svg#update', previewValue: '#update' },
  { name: 'Video', value: '/Static/dist/msds-spritemap.svg#video', previewValue: '#video' },
  { name: 'Warning', value: '/Static/dist/msds-spritemap.svg#warning', previewValue: '#warning' },
  { name: 'Webinar', value: '/Static/dist/msds-spritemap.svg#webinar', previewValue: '#webinar' },
  {
    name: 'XProtect Corporate',
    value: '/Static/dist/msds-spritemap.svg#xprotect-corporate',
    previewValue: '#xprotect-corporate'
  },
  {
    name: 'XProtect Essential Plus',
    value: '/Static/dist/msds-spritemap.svg#xprotect-essential-plus',
    previewValue: '#xprotect-essential-plus'
  },
  {
    name: 'XProtect Expert',
    value: '/Static/dist/msds-spritemap.svg#xprotect-expert',
    previewValue: '#xprotect-expert'
  },
  {
    name: 'XProtect Express Plus',
    value: '/Static/dist/msds-spritemap.svg#xprotect-express-plus',
    previewValue: '#xprotect-express-plus'
  },
  {
    name: 'XProtect Professional Plus',
    value: '/Static/dist/msds-spritemap.svg#xprotect-professional-plus',
    previewValue: '#xprotect-professional-plus'
  }
]

export const richIcons = [
  { name: 'Logo Diamond', value: 'msds-logo-diamond' },
  { name: 'Dome Cam', value: 'msds-dome-cam' },
  { name: 'Dome Cam 8', value: 'msds-dome-cam-8' },
  { name: 'Camera Group Small', value: 'msds-cam-group-small' },
  { name: 'Camera Group Big', value: 'msds-cam-group-big' },
  { name: 'Planet', value: 'msds-planet' },
  { name: 'Single Site', value: 'msds-single-site' },
  { name: 'Advanced Super Surveillance', value: 'msds-advanced-super-surveillance' },
  { name: 'Screen Recording', value: 'msds-screen-recording' },
  { name: 'Clock 24/7', value: 'msds-clock-24-7' },
  { name: 'Calendar Monthly', value: 'msds-cal-monthly' },
  { name: 'Calendar Weekly', value: 'msds-cal-weekly' },
  { name: 'Backup Important', value: 'msds-backup-important' },
  { name: 'No Backup', value: 'msds-no-backup' },
  { name: 'XProtect', value: 'msds-xprotect' },
  { name: 'Access Control Illustration', value: 'msds-access-control-illustration' },
  { name: 'Care', value: 'msds-care' },
  { name: 'Contact Illustration', value: 'msds-contact-illustration' },
  { name: 'Customizable', value: 'msds-customizable' },
  { name: 'Donwload Illustration', value: 'msds-download-illustration' },
  { name: 'End User', value: 'msds-end-user' },
  { name: 'Getting Started', value: 'msds-getting-started' },
  { name: 'Interconnect', value: 'msds-interconnect' },
  { name: 'Milestone Global Offices Illustration', value: 'msds-milestone-global-offices-illustration' },
  { name: 'Product Overview Illustration', value: 'msds-product-overview-illustration' },
  { name: 'Reliable', value: 'msds-reliable' },
  { name: 'Scalable', value: 'msds-scalable' },
  { name: 'Secure', value: 'msds-secure' },
  { name: 'Upgrade', value: 'msds-upgrade' },
  { name: 'Skyline', value: 'msds-skyline' },
  { name: 'Benefits and Requirements', value: 'msds-benefits-and-requirements' },
  { name: 'Hardware Track', value: 'msds-hardware-track' },
  { name: 'Application Track', value: 'msds-application-track' },
  { name: 'Device track', value: 'msds-device-track' },
  { name: 'System Builder Track', value: 'msds-system-builder-track' },
  { name: 'Service Track', value: 'msds-service-track' },
  { name: 'Hands', value: 'msds-hands' },
  { name: 'GDPR Info Kit', value: 'msds-gdpr-info-kit' },
  { name: 'GDPR Toolbox', value: 'msds-gdpr-toolbox' },
  { name: 'About GDPR', value: 'msds-about-gdpr' },
  { name: 'GDPR Ready', value: 'msds-gdpr-ready' },
  { name: 'Reduced Investment', value: 'msds-reduced-investment' },
  { name: 'Feature Rich', value: 'msds-feature-rich' },
  { name: 'Ease Of Use', value: 'msds-ease-of-use' },
  { name: 'Wifi', value: 'msds-wifi' },
  { name: 'Xprotect Compare Matrix', value: 'msds-xprotect-compare-matrix' },
  { name: 'Xprotect Compare Products', value: 'msds-xprotect-compare-products' },
  { name: 'Xprotect Compare Releases', value: 'msds-xprotect-compare-releases' },
  { name: 'Okay', value: 'msds-okay' },
  { name: 'Analytics', value: 'msds-analytics' },
  { name: 'Body worn', value: 'msds-body-worn' },
  { name: 'Catalogue', value: 'msds-catalogue' },
  { name: 'Community', value: 'msds-community' },
  { name: 'Crime', value: 'msds-crime' },
  { name: 'Crowd Management', value: 'msds-crowd-management' },
  { name: 'Customer Stories', value: 'msds-customer-stories' },
  { name: 'Cyber security', value: 'msds-cyber-security' },
  { name: 'Decision making', value: 'msds-decision-making' },
  { name: 'Design', value: 'msds-design' },
  { name: 'Devices', value: 'msds-devices' },
  { name: 'Document', value: 'msds-document' },
  { name: 'Emergency', value: 'msds-emergency' },
  { name: 'Employees', value: 'msds-employees' },
  { name: 'Get leads', value: 'msds-get-leads' },
  { name: 'Growth Data', value: 'msds-growth-data' },
  { name: 'Hardware, applications, software', value: 'msds-hardware-applications-software' },
  { name: 'Hardware', value: 'msds-hardware' },
  { name: 'Integrator Searching Female', value: 'msds-integrator-searching-female' },
  { name: 'Integrator Searching male', value: 'msds-integrator-searching-male' },
  { name: 'Investigation', value: 'msds-investigation' },
  { name: 'LPR', value: 'msds-lpr' },
  { name: 'Marketplace Filter', value: 'msds-marketplace-filter' },
  { name: 'Marketplace Interface', value: 'msds-marketplace-interface' },
  { name: 'Milestone In The Media', value: 'msds-milestone-in-the-media' },
  { name: 'Mobile support', value: 'msds-mobile-support' },
  { name: 'My Milestone', value: 'msds-my-milestone' },
  { name: 'Network', value: 'msds-network' },
  { name: 'Newspaper', value: 'msds-newspaper' },
  { name: 'Open Platform Community', value: 'msds-open-platform-community' },
  { name: 'Outdated Hardware', value: 'msds-outdated-hardware' },
  { name: 'Partnership', value: 'msds-partnership' },
  { name: 'Press Release', value: 'msds-press-release' },
  { name: 'Privacy', value: 'msds-privacy' },
  { name: 'Project', value: 'msds-project' },
  { name: 'Promotion', value: 'msds-promotion' },
  { name: 'Publish', value: 'msds-publish' },
  { name: 'Quote', value: 'msds-quote' },
  { name: 'Reaction mode', value: 'msds-reaction-mode' },
  { name: 'Save money', value: 'msds-save-money' }
]
