export const buttonIcons = [
  {
    name: 'Right Arrow',
    value: '/Static/dist/msds-spritemap.svg#right-arrow',
    previewValue: '#right-arrow'
  },
  { name: 'Email', value: '/Static/dist/msds-spritemap.svg#email', previewValue: '#email' },
  { name: 'Phone', value: '/Static/dist/msds-spritemap.svg#phone', previewValue: '#phone' },
  { name: 'Linkedin', value: '/Static/dist/msds-spritemap.svg#linkedin', previewValue: '#linkedin' },
  { name: 'Publish', value: '/Static/dist/msds-spritemap.svg#publish', previewValue: '#publish' },
  { name: 'Cross', value: '/Static/dist/msds-spritemap.svg#cross', previewValue: '#cross' },
  { name: 'Quote', value: '/Static/dist/msds-spritemap.svg#quote', previewValue: '#quote' },
  { name: 'Download', value: '/Static/dist/msds-spritemap.svg#download', previewValue: '#download' },
  { name: 'Checkmark', value: '/Static/dist/msds-spritemap.svg#checkmark', previewValue: '#checkmark' }
]

export const richIcons = [
  { name: 'Logo Diamond', value: 'msds-logo-diamond' },
  { name: 'Dome Cam', value: 'msds-dome-cam' },
  { name: 'Dome Cam 8', value: 'msds-dome-cam-8' },
  { name: 'Camera Group Small', value: 'msds-cam-group-small' },
  { name: 'Camera Group Big', value: 'msds-cam-group-big' },
  { name: 'Planet', value: 'msds-planet' },
  { name: 'Single Site', value: 'msds-single-site' },
  { name: 'Advanced Super Surveillance', value: 'msds-advanced-super-surveillance' },
  { name: 'Screen Recording', value: 'msds-screen-recording' },
  { name: 'Clock 24/7', value: 'msds-clock-24-7' },
  { name: 'Calendar Monthly', value: 'msds-cal-monthly' },
  { name: 'Calendar Weekly', value: 'msds-cal-weekly' },
  { name: 'Backup Important', value: 'msds-backup-important' },
  { name: 'No Backup', value: 'msds-no-backup' },
  { name: 'XProtect', value: 'msds-xprotect' },
  { name: 'Access Control Illustration', value: 'msds-access-control-illustration' },
  { name: 'Care', value: 'msds-care' },
  { name: 'Contact Illustration', value: 'msds-contact-illustration' },
  { name: 'Customizable', value: 'msds-customizable' },
  { name: 'Donwload Illustration', value: 'msds-download-illustration' },
  { name: 'End User', value: 'msds-end-user' },
  { name: 'Getting Started', value: 'msds-getting-started' },
  { name: 'Interconnect', value: 'msds-interconnect' },
  { name: 'Milestone Global Offices Illustration', value: 'msds-milestone-global-offices-illustration' },
  { name: 'Product Overview Illustration', value: 'msds-product-overview-illustration' },
  { name: 'Reliable', value: 'msds-reliable' },
  { name: 'Scalable', value: 'msds-scalable' },
  { name: 'Secure', value: 'msds-secure' },
  { name: 'Upgrade', value: 'msds-upgrade' },
  { name: 'Skyline', value: 'msds-skyline' },
  { name: 'Benefits and Requirements', value: 'msds-benefits-and-requirements' },
  { name: 'Hardware Track', value: 'msds-hardware-track' },
  { name: 'Application Track', value: 'msds-application-track' },
  { name: 'Device track', value: 'msds-device-track' },
  { name: 'System Builder Track', value: 'msds-system-builder-track' },
  { name: 'Service Track', value: 'msds-service-track' },
  { name: 'Hands', value: 'msds-hands' },
  { name: 'GDPR Info Kit', value: 'msds-gdpr-info-kit' },
  { name: 'GDPR Toolbox', value: 'msds-gdpr-toolbox' },
  { name: 'About GDPR', value: 'msds-about-gdpr' },
  { name: 'GDPR Ready', value: 'msds-gdpr-ready' },
  { name: 'Reduced Investment', value: 'msds-reduced-investment' },
  { name: 'Feature Rich', value: 'msds-feature-rich' },
  { name: 'Ease Of Use', value: 'msds-ease-of-use' },
  { name: 'Wifi', value: 'msds-wifi' }
]
