export const buttonIcons = ['right-arrow', 'email', 'phone', 'linkedin', 'publish', 'cross', 'quote', 'download']

export const richIcons = [
  'logo-diamond',
  'dome-cam',
  'dome-cam-8',
  'cam-group-small',
  'cam-group-big',
  'planet',
  'single-site',
  'advanced-super-surveillance',
  'screen-recording',
  'clock-24-7',
  'cal-monthly',
  'cal-weekly',
  'backup-important',
  'no-backup',
  'xprotect',
  'access-control-illustration',
  'care',
  'contact-illustration',
  'customizable',
  'download-illustration',
  'end-user',
  'getting-started',
  'interconnect',
  'milestone-global-offices-illustration',
  'product-overview-illustration',
  'reliable',
  'scalable',
  'secure',
  'upgrade',
  'skyline'
]
