import '../scss/main.scss'
import 'components/tab-tile/tab-tile.js'
import 'components/forms/text-areas/text-area.js'
import 'components/alert/alert.js'
import 'components/button-cards/card.js'
import 'components/button-cards/generic-card/generic-card.js'
import 'components/button-cards/contact-card/contact-card.js'
import 'components/button-cards/solution-card/solution-card.js'
import 'components/button-cards/_category-card/category-card.js'
import 'components/colors/background-colors.js'
import 'components/colors/text-colors.js'

