export const fontColors = [
  { name: 'Milestone Clear Blue', value: 'msds-text-clear-blue' },
  { name: 'Milestone Dark Blue', value: 'msds-text-dark-blue' },
  { name: 'Milestone Yellow', value: 'msds-text-yellow' },
  { name: 'Gray 1', value: 'msds-text-gray-1' },
  { name: 'Gray 2', value: 'msds-text-gray-1' },
  { name: 'Gray 3', value: 'msds-text-gray-3' },
  { name: 'Gray 4', value: 'msds-text-gray-4' },
  { name: 'Gray 5', value: 'msds-text-gray-5' },
  { name: 'Gray 6', value: 'msds-text-gray-6' },
  { name: 'Gray 7', value: 'msds-text-gray-7' },
  { name: 'Gray 8', value: 'msds-text-gray-8' },
  { name: 'Gray 9', value: 'msds-text-gray-9' },
  { name: 'Gray 10', value: 'msds-text-gray-10' },
  { name: 'White', value: 'msds-text-white' },
  { name: 'Black', value: 'msds-text-black' },
  { name: 'Alt Blue 1', value: 'msds-text-alt-blue-1' },
  { name: 'Alt Blue 2', value: 'msds-text-alt-blue-2' },
  { name: 'Alt Blue 3', value: 'msds-text-alt-blue-3' },
  { name: 'Alt Yellow 1', value: 'msds-text-alt-yellow-1' },
  { name: 'Alt Yellow 2', value: 'msds-text-alt-yellow-2' },
  { name: 'Confirm Green', value: 'msds-text-confirm-green' },
  { name: 'Danger Red 1', value: 'msds-text-danger-red-1' },
  { name: 'Danger Red 2', value: 'msds-text-danger-red-2' },
  { name: 'Sand', value: 'msds-text-sand' }
]

export const backgroundColors = [
  { name: 'White', value: 'msds-bg-white' },
  { name: 'Gray 2', value: 'msds-bg-gray-1' },
  { name: 'Gray 3', value: 'msds-bg-gray-3' },
  { name: 'Gray 4', value: 'msds-bg-gray-4' },
  { name: 'Gray 5', value: 'msds-bg-gray-5' },
  { name: 'Gray 8', value: 'msds-bg-gray-8' },
  { name: 'Gray 9', value: 'msds-bg-gray-9' },
  { name: 'Gray 10', value: 'msds-bg-gray-10' },
  { name: 'Milestone Yellow', value: 'msds-bg-yellow' },
  { name: 'Milestone Clear Blue', value: 'msds-bg-clear-blue' },
  { name: 'Milestone Dark Blue', value: 'msds-bg-dark-blue' },
  { name: 'Orange', value: 'msds-bg-orange' },
  { name: 'Dusty Green', value: 'msds-bg-dusty-green' },
  { name: 'Husky Dark Blue', value: 'msds-bg-husky-dark-blue' },
  { name: 'White Gradient', value: 'msds-bg-white-gradient' },
  { name: 'White Gradient Reverse', value: 'msds-bg-white-gradient-reverse' },
  { name: 'Gray Gradient 1', value: 'msds-bg-gray-gradient-1' },
  { name: 'Gray Gradient 2', value: 'msds-bg-gray-gradient-2' },
  { name: 'Gray Gradient 3', value: 'msds-bg-gray-gradient-3' },
  { name: 'Gray Gradient 4', value: 'msds-bg-gray-gradient-4' },
  { name: 'Gray Gradient 5', value: 'msds-bg-gray-gradient-5' },
  { name: 'Gray Gradient 6', value: 'msds-bg-gray-gradient-6' },
  { name: 'Gray Gradient 6 Reverse', value: 'msds-bg-gray-gradient-6-reverse' },
  { name: 'Yellow Gradient', value: 'msds-bg-yellow-gradient' },
  { name: 'Blue To Yellow Gradient', value: 'msds-bg-blue-to-yellow-gradient' },
  { name: 'Clear Blue Gradient', value: 'msds-bg-clear-blue-gradient' },
  { name: 'Clear Blue Gradient 2', value: 'msds-bg-clear-blue-gradient-2' },
  { name: 'Clear Blue Gradient 2 Reverse', value: 'msds-bg-clear-blue-gradient-2-reverse' },
  { name: 'Dark Blue Gradient', value: 'msds-bg-dark-blue-gradient' },
  { name: 'Dark Blue Gradient 2', value: 'msds-bg-dark-blue-gradient-2' },
  { name: 'Dark Blue Gradient 2 Reverse', value: 'msds-bg-dark-blue-gradient-2-reverse' },
  { name: 'Mixed Blue Gradient', value: 'msds-bg-mixed-blue-gradient' },
  { name: 'Husky Dark Blue Gradient', value: 'msds-bg-husky-dark-blue-gradient' }
]
